# Generated by Django 5.0.2 on 2024-02-11 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_category_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_profile",
                    models.ImageField(null=True, upload_to="media/author/"),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("about_author", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(null=True, upload_to="media/featured_image/"),
                ),
                ("featured_video", models.CharField(max_length=300, null=True)),
                ("title", models.CharField(max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("description", models.TextField(null=True)),
                ("price", models.IntegerField(null=True)),
                ("discount", models.IntegerField(null=True)),
                (
                    "slug",
                    models.SlugField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Published", "Published"),
                            ("Pending", "Pending"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.categories",
                    ),
                ),
            ],
        ),
    ]
